name: release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release-version:
        description: "A valid Semver version string"
        required: true

permissions:
  contents: write
  pull-requests: write
  id-token: write

concurrency:
  group: "release-${{ github.ref }}"
  cancel-in-progress: false

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  check-version:
    # Only run version check for manual releases
    if: github.event_name == 'workflow_dispatch' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: version
        run: |
          version=$(git describe --abbrev=0 --tags)
          echo $version
          echo "version=${version}" >> $GITHUB_OUTPUT

      - name: Semver check
        id: semver_check
        uses: madhead/semver-utils@v4
        with:
          lenient: false
          version: ${{ inputs.release-version }}
          compare-to: ${{ steps.version.outputs.version }}

      - name: Semver ok
        if: steps.semver_check.outputs.comparison-result != '>'
        run: |
          echo "The release version is not valid Semver (${{ inputs.release-version }}) that is greater than the current version ${{ steps.version.outputs.version }}."
          exit 1

  release:
    needs: test
    # For manual releases, also need version check
    if: always() && needs.test.result == 'success' && (needs.check-version.result == 'success' || needs.check-version.result == 'skipped')
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --frozen --all-groups --python 3.12

      - name: Determine version
        id: version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "version=${{ inputs.release-version }}" >> $GITHUB_OUTPUT
          else
            # For automatic releases, use semantic versioning
            # Get the latest tag
            latest_tag=$(git describe --abbrev=0 --tags 2>/dev/null || echo "v0.0.0")
            echo "Latest tag: $latest_tag"
            
            # Check commit messages for version bump type
            commits=$(git log ${latest_tag}..HEAD --pretty=format:"%s")
            echo "Commits since last tag:"
            echo "$commits"
            
            # Determine version bump based on conventional commits
            if echo "$commits" | grep -q "^feat\|^BREAKING CHANGE"; then
              # Minor version bump for features
              new_version=$(echo $latest_tag | sed 's/v//' | awk -F. '{print "v" ($1"."($2+1)".0")}')
            elif echo "$commits" | grep -q "^fix\|^perf"; then
              # Patch version bump for fixes
              new_version=$(echo $latest_tag | sed 's/v//' | awk -F. '{print "v" $1"."$2"."($3+1)}')
            else
              echo "No version-bumping commits found, skipping release"
              exit 0
            fi
            
            echo "version=$new_version" >> $GITHUB_OUTPUT
          fi

      - name: Update version in pyproject.toml
        run: |
          version="${{ steps.version.outputs.version }}"
          # Remove 'v' prefix if present
          version=${version#v}

          # Update version in pyproject.toml
          sed -i "s/version = \"[^\"]*\"/version = \"$version\"/" pyproject.toml

          # Commit the version change
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add pyproject.toml
          git commit -m "chore: bump version to $version" || echo "No changes to commit"

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          toTag: "main"
          configuration: ".github/changelog_config.json"

      - name: Create and push git tag
        run: |
          version="${{ steps.version.outputs.version }}"

          # Tag the release
          git tag -a "$version" -m "Release version $version"

          # Push the changes and tags
          git push origin main
          git push origin "$version"

      - name: Build the wheel and sdist
        run: uv build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          tag_name: ${{ steps.version.outputs.version }}
          body: ${{steps.github_release.outputs.changelog}}
